### ISSUE TITLE
Plugin not working after update to 3.0

### ISSUE THREAD

**Issue by Rhineberry** [RaresAil/homebridge-levoit-air-purifier#95] opened 2024-04-16 01:46 UTC
### Describe The Bug

Levoit air purifier no longer responds in HomeKit after upgrade to version 3. Will not turn on or off, or update air quality readings. 

### Expected behavior

Purifier turns on and off via Homekit.
Air quality value updates. 

### Logs

[Levoit Air Purifier Bridge 7CED@Levoit Air Purifier@@Active] characteristic value expected valid finite number and received "undefined" (undefined)

### Plugin Config

{
  "accessories" : [

  ],
  "platforms" : [
    {
      "email" : "redacted@mac.com",
      "name" : "Levoit Air Purifiers",
      "password" : "redacted",
      "platform" : "LevoitAirPurifiers",
      "plugin_map" : {
        "plugin_name" : "homebridge-levoit-air-purifier"
      }
    }
  ]
}

### Plugin Version

3.0

### Homebridge Version

1.7.0

### Node.js Version

16.20.2

### NPM Version

No idea

### Operating System

HOOBS 4.3.1 on raspberry pi

**Comment by RaresAil** [comment] 2024-04-16 05:15
Hey, i know about a bug that the turn off and on is not working, but the other features should work fine

**Comment by leeladisky** [comment] 2024-04-17 16:17
Exact same problem here... power on/off isn't working.

**Comment by RaresAil** [comment] 2024-04-17 19:08
Duplicate of #94 and will be fixed in v3.0.1

**Closed by RaresAil** 2024-04-17 19:08 UTC
Labels: Bug
