### ISSUE TITLE
Multiple devices unresponsive

### ISSUE THREAD

**Issue by Gotcha182** [RaresAil/homebridge-levoit-air-purifier#66] opened 2023-05-07 08:10 UTC
### Describe The Bug

I have multiple humidifiers between the core 200 300 and 400 and all are showing as unresponsive now. 

### Expected behavior

Operational devices and to be able to control them though the home app

### Logs

![IMG_6327](https://user-images.githubusercontent.com/44763527/236665392-5c9ba9bc-f3be-4dcc-aeab-907aba3f9f99.jpeg)

### Plugin Config

Can add if needed specifically

### Plugin Version

1.3.0

### Homebridge Version

1.6.1

### Node.js Version

18.16.0

### NPM Version

9.5.1

### Operating System

Homebridge image on raspberry pi 4

**Comment by RaresAil** [comment] 2023-05-07 08:13
Hello, that is a homebridge issue, it should've been fixed in 1.6.1, try changing the advertiser, or if the issue persists downgrade to 1.5.x.

Duplicate of https://github.com/RaresAil/homebridge-levoit-air-purifier/issues/64

**Closed** 2023-05-07 18:48 UTC
Labels: Homebridge Issue
